INSERT INTO vehicles (brand, model, year, color, transmission, km, seats, doors, sellery, origin, volant, clim, city, engine, power, images, "desc", in_stock) 
VALUES 
('Toyota', 'Corolla', 2020, 'bleu', 'Automatique', 45000, 5, 5, 'cuir', 'Belgique', 'gauche, direct', 'bon état, d''origine', 'Douala', '2.0L TDI', '15CV', '["/hero-bg.jpg", "hero-catalogue.jpg"]', 'Véhicule très propre importé récemment de Belgique. Aucun frais à prévoir. Carrosserie intacte, moteur en parfait état, pneus neufs, climatisation fonctionnelle. Convient pour un usage familial ou professionnel.', 1),
('Honda', 'Civic', 2019, 'noir', 'Manuelle', 55000, 5, 4, 'tissu', 'Japon', 'gauche', 'fonctionnelle', 'Yaoundé', '1.8L i-VTEC', '140CV', '["/civic-hero.jpg", "civic-catalogue.jpg"]', 'Voiture compacte avec faible consommation. Idéale pour les trajets urbains.', 1),
('Ford', 'Focus', 2018, 'blanc', 'Automatique', 60000, 5, 4, 'cuir', 'USA', 'gauche', 'bon état', 'Douala', '2.0L EcoBoost', '160CV', '["/focus-hero.jpg", "focus-catalogue.jpg"]', 'Berline familiale avec un moteur puissant et économique en carburant.', 1),
('Volkswagen', 'Golf', 2021, 'gris', 'Automatique', 10000, 5, 5, 'tissu', 'Allemagne', 'gauche', 'neuve', 'Yaoundé', '1.6L TDI', '115CV', '["/golf-hero.jpg", "golf-catalogue.jpg"]', 'Compacte et sportive, idéale pour une conduite en ville.', 1),
('BMW', 'X5', 2020, 'noir', 'Automatique', 20000, 5, 5, 'cuir', 'Allemagne', 'gauche', 'haut de gamme', 'Douala', '3.0L Turbo', '265CV', '["/x5-hero.jpg", "x5-catalogue.jpg"]', 'SUV haut de gamme offrant confort et performance exceptionnels.', 1),
('Mercedes-Benz', 'A-Class', 2021, 'argent', 'Automatique', 15000, 5, 5, 'cuir', 'Allemagne', 'gauche', 'neuve', 'Yaoundé', '2.0L AMG', '200CV', '["/aclass-hero.jpg", "aclass-catalogue.jpg"]', 'Compacte sportive avec une conduite fluide et un design élégant.', 1),
('Nissan', 'Qashqai', 2020, 'bleu', 'Automatique', 30000, 5, 5, 'tissu', 'Japon', 'gauche', 'fonctionnelle', 'Douala', '1.5L dCi', '130CV', '["/qashqai-hero.jpg", "qashqai-catalogue.jpg"]', 'SUV spacieux et confortable pour les trajets longs.', 1),
('Audi', 'A3', 2019, 'blanc', 'Manuelle', 40000, 5, 5, 'cuir', 'Allemagne', 'gauche', 'bon état', 'Yaoundé', '1.6L TDI', '150CV', '["/a3-hero.jpg", "a3-catalogue.jpg"]', 'Berline compacte idéale pour les trajets quotidiens.', 1),
('Peugeot', '3008', 2018, 'argent', 'Automatique', 65000, 5, 5, 'tissu', 'France', 'gauche', 'fonctionnelle', 'Douala', '1.6L HDI', '120CV', '["/3008-hero.jpg", "3008-catalogue.jpg"]', 'SUV familial avec beaucoup de place et une conduite agréable.', 1);
